### ISSUE TITLE
Banner Issue

### ISSUE THREAD

**Issue by SatheeshD1** [Rajavasanthan/online-delivery-pwa#1]

**Comment by SatheeshD1** [comment]
Hi @Rajavasanthan  sir,

Banner Issue(while shaking screen in wide angle) is fixed in below PR itself. Its already merged.
https://github.com/Rajavasanthan/online-delivery-pwa/pull/3

Your chrome browser version is low. Because of that only it is not working for you.
Kindly update your chrome browser and check that issue.

**Video Proof Attached:** (kindly open video in chrome browser and check)
[Banner Issue fixed proof.zip](https://github.com/Rajavasanthan/online-delivery-pwa/files/4981047/Banner.Issue.fixed.proof.zip)

Regards,
Satheesh.D

**Comment by Rajavasanthan** [comment]
Awesome..
I will check this on Wednesday during live session

**Comment by SatheeshD1** [comment]
Thank you
